# Generated by Django 4.0.1 on 2022-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=12)),
                ('guests', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('reservationDate', models.DateField()),
            ],
        ),
    ]
